### ISSUE TITLE
Double Scroll Bar

### ISSUE THREAD

**Issue by anthonykluu** [caojoshua/ZotBins-Web-App#2]
There is a double scroll bar when you go to waste guide. Not sure if this is a zotbins issue or a tippers issue
![problem](https://user-images.githubusercontent.com/34197266/57328919-95784200-70c7-11e9-85d4-721041c8a582.PNG)

**Comment by okyang** [comment]
I think that it's because the zotbins website is embedded into to the TIPPERS portal.
